name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install .[dev]
      - name: Check code style
        run: black --line-length 120 fromenv tests
      - name: Lint the code
        run: flake8 fromenv tests --count --max-complexity=10 --max-line-length=120 --statistics